eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  cloud:
    config:
      override-system-properties: false #in order to not override the configs that exist in that service

