spring:
  mongodb:
    username: user
    password: user123
    host: localhost
    port: 27017
    database: customer-db
    authentication-database: admin

  kafka:
    consumer:
      bootstrap-servers: localhost:9092 #the same configs we put for kafka server
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer #to tell Kafka what is the serializer of our msgs
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*' # * is used in development end
        spring.json.type.mapping: orderConfirmation:com.skymat.ecommerce.kafka.OrderConfirmation,paymentConfirmation:com.skymat.ecommerce.notification.PaymentNotificationRequest #the producer should inform the consumer what is the object that is being sent
  mail:
    host: localhost
    port: 1025
    username: rita
    password: rit123
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled:true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 500  #5sec

server:
  port: 8040