spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: user123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: localhost:9092 #the same configs we put for kafka server
      key-serializer: org.apache.kafka.common.serialization.StringSerializer #to tell Kafka what is the serializer of our msgs
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.skymat.ecommerce.notification.PaymentNotificationRequest #the producer should inform the consumer what is the object that is being sent
server:
  port: 8060